runtime: python312

entrypoint: gunicorn -b :$PORT flask_server:app

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5
  min_pending_latency: 100ms
  max_pending_latency: automatic
  max_concurrent_requests: 5

env_variables:
  PYTHONUNBUFFERED: "1"

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always
