runtime: python312

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:    # Standard supports automatic_scaling
  min_instances: 0
  max_instances: 2

env_variables:
  PYTHON_VERSION: "3.12"
