runtime: python312

instance_class: F1

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5
  min_pending_latency: 100ms
  max_pending_latency: automatic
  max_concurrent_requests: 5

env_variables:
  PYTHON_VERSION: "3.12"
